version: '3.8'

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${CONTAINER_NAME}-mariadb
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb/data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_NAME}-phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${CONTAINER_NAME}-mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
    depends_on:
      - mariadb
    restart: always